services:
  - type: web
    name: behavior-auth-api
    runtime: python
    repo: https://github.com/OFF-rtk/behavior-auth-backend
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
