services:
  - type: web
    name: behavior-auth-backend
    env: python
    runtime: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./startup.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"

