services:
  - type: web
    name: behavior-auth-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./startup.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
